import { createFarmerSchema, LANGUAGES, type CreateFarmer } from '@agri-erp/shared';

/**
 * REGISTERING A FARMER, AS THE ROUTE DEFINES IT.
 *
 * `POST /api/farmers` accepts admin and officer, and for an officer it is
 * stricter than the schema alone:
 *
 *   1. `payam_id` MUST equal `auth.scope.payamId`, or 403. An officer registers
 *      in their own payam and nowhere else (C-5.1). There is therefore nothing
 *      for them to choose, which is why this model takes the payam from the
 *      session rather than from a picker.
 *   2. `registered_by`, if sent at all, must equal the caller. An officer sends
 *      nothing and the route stamps them; sending somebody else's id is 403.
 *   3. `consent.granted` must be `true`, or 422 `consent_required`. The schema
 *      marks consent optional and the ROUTE does not -- so the form requires it.
 *   4. `id` is generated by the CLIENT and is the idempotency key (C-9.2): a
 *      retry of a registration that already landed returns 200 with the stored
 *      record rather than a second farmer.
 *
 * The farmer number is not here and must not be: `allocateFarmerNumber` assigns
 * it from the county inside the transaction, and the screen reads it off the
 * response.
 */

export type ConsentLanguage = (typeof LANGUAGES)[number];

/** The revision of the consent statement itself, independent of language. */
const CONSENT_TEXT_REVISION = 'v1.0';

/**
 * The consent text version each language points at, DERIVED rather than typed
 * out.
 *
 * It used to be a literal map, and that made this file one of four places
 * naming the languages by hand. When the project moved from Juba Arabic to
 * standard Arabic the shared enum was renamed and every hand-written copy
 * became wrong at once -- a seam that only a type error caught, and only at
 * merge.
 *
 * So the table is now generated from `LANGUAGES`, the canonical list the API's
 * own `z.enum` is built from. There is no language identifier written down in
 * this file at all: rename the value in `packages/shared` and this follows,
 * with nothing here to remember to edit.
 *
 * The convention it encodes is the repository's, `v1.0-<language>`, as written
 * by hand in `components/farmers/RegisterFarmer.tsx`. `registration.test.ts`
 * holds the derivation against that file, so a language that ever needs a
 * different revision fails the gate instead of being silently mislabelled.
 */
export const CONSENT_VERSION: Record<ConsentLanguage, string> = Object.fromEntries(
  LANGUAGES.map((language) => [language, `${CONSENT_TEXT_REVISION}-${language}`]),
) as Record<ConsentLanguage, string>;

export interface RegistrationDraft {
  given_name: string;
  family_name: string;
  sex: 'f' | 'm';
  year_of_birth: string;
  phone: string;
  /** '' means the farmer has none; the field is optional on the contract. */
  national_id: string;
  consent_language: ConsentLanguage | '';
  consent_granted: boolean;
}

export const emptyDraft = (): RegistrationDraft => ({
  given_name: '',
  family_name: '',
  sex: 'f',
  year_of_birth: '',
  phone: '',
  national_id: '',
  consent_language: '',
  consent_granted: false,
});

/**
 * The body, built from the draft and the SESSION -- never from a picker.
 *
 * `payam_id` comes from the officer's own scope and `registered_by` is omitted
 * entirely, so neither can be steered by anything on the screen. A hidden input
 * would be a value the browser could edit; a value that is never read from the
 * page cannot be.
 *
 * ABSENT IS NOT NULL. `national_id` is optional on the contract: an empty box
 * means the key is LEFT OUT, not sent as null. Sending null would be the
 * officer stating "this farmer has no identity document", which is a different
 * claim from not having asked.
 */
export function buildRegistration(
  draft: RegistrationDraft,
  payamId: string,
  newId: () => string,
): CreateFarmer {
  const body: Record<string, unknown> = {
    id: newId(),
    given_name: draft.given_name.trim(),
    family_name: draft.family_name.trim(),
    sex: draft.sex,
    year_of_birth: Number(draft.year_of_birth),
    phone: draft.phone.trim(),
    payam_id: payamId,
  };
  const nationalId = draft.national_id.trim();
  if (nationalId !== '') body.national_id = nationalId;
  if (draft.consent_language !== '') {
    body.consent = {
      text_version: CONSENT_VERSION[draft.consent_language],
      language: draft.consent_language,
      granted: draft.consent_granted,
    };
  }
  return body as CreateFarmer;
}

export interface DraftProblem {
  readonly field: keyof RegistrationDraft | 'consent';
  readonly message: string;
}

/**
 * What the officer must still do, checked against the shared schema plus the
 * route's own consent rule.
 *
 * The schema does the field work so the messages are the project's, not new
 * wording invented here. Consent is added because the ROUTE refuses without it
 * while the schema would let it through -- a form that only trusted the schema
 * would send a body that comes back 422.
 */
export function draftProblems(draft: RegistrationDraft, payamId: string | null): DraftProblem[] {
  const problems: DraftProblem[] = [];
  if (!payamId) {
    problems.push({
      field: 'consent',
      message: 'Your payam is not known, so a farmer cannot be registered from this session.',
    });
    return problems;
  }
  const body = buildRegistration(draft, payamId, () => '00000000-0000-4000-8000-000000000000');
  const parsed = createFarmerSchema.safeParse(body);
  if (!parsed.success) {
    for (const issue of parsed.error.issues) {
      const field = String(issue.path[0] ?? '') as DraftProblem['field'];
      problems.push({ field, message: issue.message });
    }
  }
  if (draft.consent_language === '') {
    problems.push({ field: 'consent', message: 'Choose the language the consent was read in.' });
  } else if (!draft.consent_granted) {
    problems.push({
      field: 'consent',
      message: 'The farmer must give consent before the record can be created.',
    });
  }
  return problems;
}
