import { z } from 'zod';
import { LANGUAGES } from './learning';
import { phoneSchema } from './phone';

/**
 * The farmer record (C-5). One definition of what is valid, used by the API
 * and by the officer's app, so the two cannot disagree (C-5.2).
 *
 * Every reason here is pinned in CONVENTIONS.md §5.2.3. Every sentence is
 * ours; none is generated by the validation library.
 */

export const SEXES = ['f', 'm'] as const;
export type Sex = (typeof SEXES)[number];

export const VERIFICATION_STATUSES = ['pending', 'verified', 'rejected'] as const;
export type VerificationStatus = (typeof VERIFICATION_STATUSES)[number];

/** `self` exists because the data model has it. No route produces it. */
export const REGISTRATION_SOURCES = ['officer', 'self'] as const;
export type RegistrationSource = (typeof REGISTRATION_SOURCES)[number];

export const FARMER_LIMITS = {
  nameMax: 100,
  /** Not more than this many years past (C-5.2). */
  maxAgeYears: 120,
  nationalIdMin: 6,
  nationalIdMax: 20,
  consentTextVersionMax: 32,
} as const;

export const FARMER_MESSAGES = {
  reassignOfficerRequired: 'Name the officer who will now work with this farmer.',
  reassignOfficerNotUuid: 'The officer identifier is not in the expected form.',
  idRequired: 'A registration must carry its identifier.',
  idNotUuid: 'The identifier is not in the expected form.',
  givenNameRequired: 'Enter the given name.',
  familyNameRequired: 'Enter the family name.',
  nameTooLong: 'A name can be at most 100 characters.',
  nameNotLetters: 'A name contains letters, spaces, apostrophes and hyphens only.',
  sexInvalid: 'Choose f or m.',
  yearNotWhole: 'The year of birth must be a whole number.',
  yearInFuture: 'The year of birth cannot be in the future.',
  yearTooFarBack: 'The year of birth cannot be more than 120 years ago.',
  nationalIdShape: 'A national ID is 6 to 20 characters: digits and capital letters only.',
  payamRequired: 'Choose a payam.',
  officerNotUuid: 'The registering officer is not in the expected form.',
  consentNotObject: 'Consent must be recorded as an object.',
  consentTextVersionRequired: 'Record which consent text was read.',
  consentTextVersionTooLong: 'The consent text version can be at most 32 characters.',
  consentLanguageInvalid: 'Choose en or ar for the consent language.',
  consentGrantedNotBoolean: 'Say whether consent was granted, true or false.',
  filterStatusInvalid: 'Choose pending, verified or rejected.',
  filterDateInvalid: 'Give the date as an ISO 8601 timestamp.',
  capturedAtInvalid: 'Record when the registration was captured as a date and time.',
  filterDuplicateInvalid: 'Choose true or false.',
  filterRangeInverted: 'The end of the date range is before its start.',
} as const;

/** Letters (any script), combining marks, spaces, apostrophes, hyphens. No digits, no emoji. */
const NAME_PATTERN = /^[\p{L}\p{M}\s'’-]+$/u;

const nameSchema = (required: string) =>
  z
    .string({ error: () => required })
    .trim()
    .min(1, required)
    .max(FARMER_LIMITS.nameMax, FARMER_MESSAGES.nameTooLong)
    .regex(NAME_PATTERN, FARMER_MESSAGES.nameNotLetters);

export const givenNameSchema = nameSchema(FARMER_MESSAGES.givenNameRequired);
export const familyNameSchema = nameSchema(FARMER_MESSAGES.familyNameRequired);

export const sexSchema = z.enum(SEXES, { error: () => FARMER_MESSAGES.sexInvalid });

/** Evaluated at validation time, so a schema built in 2026 is still right in 2027. */
export const yearOfBirthSchema = z
  .number({ error: () => FARMER_MESSAGES.yearNotWhole })
  .int(FARMER_MESSAGES.yearNotWhole)
  .superRefine((year, ctx) => {
    const thisYear = new Date().getUTCFullYear();
    if (year > thisYear) {
      ctx.addIssue({ code: 'custom', message: FARMER_MESSAGES.yearInFuture });
    } else if (year < thisYear - FARMER_LIMITS.maxAgeYears) {
      ctx.addIssue({ code: 'custom', message: FARMER_MESSAGES.yearTooFarBack });
    }
  });

/**
 * Reserved shape (CONVENTIONS §7): no official format is documented. Corrected
 * when CORWADO supplies one.
 */
export const NATIONAL_ID_PATTERN = /^[0-9A-Z]{6,20}$/;
export const nationalIdSchema = z
  .string({ error: () => FARMER_MESSAGES.nationalIdShape })
  .trim()
  .regex(NATIONAL_ID_PATTERN, FARMER_MESSAGES.nationalIdShape);

const uuidSchema = (message: string) =>
  z
    .string({ error: () => message })
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, message);

export const consentInputSchema = z.strictObject(
  {
    text_version: z
      .string({ error: () => FARMER_MESSAGES.consentTextVersionRequired })
      .trim()
      .min(1, FARMER_MESSAGES.consentTextVersionRequired)
      .max(FARMER_LIMITS.consentTextVersionMax, FARMER_MESSAGES.consentTextVersionTooLong),
    language: z.enum(LANGUAGES, { error: () => FARMER_MESSAGES.consentLanguageInvalid }),
    granted: z.boolean({ error: () => FARMER_MESSAGES.consentGrantedNotBoolean }),
  },
  { error: () => FARMER_MESSAGES.consentNotObject },
);

/**
 * Consent is OPTIONAL here on purpose: a body without it is valid input, and
 * the route answers 422 `consent_required`, a business rule not met (C-5.3).
 */
export const createFarmerSchema = z.strictObject({
  id: uuidSchema(FARMER_MESSAGES.idNotUuid),
  given_name: givenNameSchema,
  family_name: familyNameSchema,
  sex: sexSchema,
  year_of_birth: yearOfBirthSchema,
  phone: phoneSchema,
  national_id: nationalIdSchema.nullable().optional(),
  payam_id: z
    .string({ error: () => FARMER_MESSAGES.payamRequired })
    .trim()
    .min(1, FARMER_MESSAGES.payamRequired),
  /** Admin only: the officer who registered this farmer. An officer never sends it. */
  registered_by: uuidSchema(FARMER_MESSAGES.officerNotUuid).optional(),
  consent: consentInputSchema.optional(),
  /** The device's moment (C-9.10). Nullable: a record without it reads "not recorded". */
  captured_at: z
    .string({ error: () => FARMER_MESSAGES.capturedAtInvalid })
    .datetime({ offset: true, message: FARMER_MESSAGES.capturedAtInvalid })
    .nullable()
    .optional(),
});

export const patchFarmerSchema = z.strictObject({
  given_name: givenNameSchema.optional(),
  family_name: familyNameSchema.optional(),
  sex: sexSchema.optional(),
  year_of_birth: yearOfBirthSchema.optional(),
  phone: phoneSchema.optional(),
  national_id: nationalIdSchema.nullable().optional(),
  payam_id: z
    .string({ error: () => FARMER_MESSAGES.payamRequired })
    .trim()
    .min(1, FARMER_MESSAGES.payamRequired)
    .optional(),
});

const isoTimestamp = z
  .string({ error: () => FARMER_MESSAGES.filterDateInvalid })
  .datetime({ offset: true, message: FARMER_MESSAGES.filterDateInvalid });

/** Query-string filters on GET /api/farmers (C-5.7). Strings, because they arrive as strings. */
export const farmerFilterSchema = z
  .strictObject({
    verification_status: z
      .enum(VERIFICATION_STATUSES, { error: () => FARMER_MESSAGES.filterStatusInvalid })
      .optional(),
    payam: z.string().trim().min(1).optional(),
    county: z.string().trim().min(1).optional(),
    sex: sexSchema.optional(),
    registered_from: isoTimestamp.optional(),
    registered_to: isoTimestamp.optional(),
    /** C-9.9: rows whose server moment of last change is after this. */
    updated_since: isoTimestamp.optional(),
    duplicate_flag: z
      .enum(['true', 'false'], { error: () => FARMER_MESSAGES.filterDuplicateInvalid })
      .optional(),
    limit: z.string().optional(),
    cursor: z.string().optional(),
  })
  .superRefine((value, ctx) => {
    if (value.registered_from && value.registered_to) {
      if (Date.parse(value.registered_to) < Date.parse(value.registered_from)) {
        ctx.addIssue({
          code: 'custom',
          path: ['registered_to'],
          message: FARMER_MESSAGES.filterRangeInverted,
        });
      }
    }
  });

export type CreateFarmer = z.infer<typeof createFarmerSchema>;
export type PatchFarmer = z.infer<typeof patchFarmerSchema>;
export type FarmerFilter = z.infer<typeof farmerFilterSchema>;
export type ConsentInput = z.infer<typeof consentInputSchema>;

/**
 * How two names are compared for the duplicate warning (C-5.6): trimmed,
 * Unicode-normalised (NFC), lower-cased. Comparison only — the stored value is
 * exactly what was supplied (C-2.8). The database index uses the same three
 * steps in the same order, so a match here is a match there.
 */
export const nameMatchKey = (name: string): string => name.trim().normalize('NFC').toLowerCase();

/** `CE-JUB-000123`: the county code, a hyphen, six digits (C-5.4). */
export const FARMER_NUMBER_PATTERN = /^[A-Z]{2}-[A-Z]{3}-[0-9]{6}$/;
export const formatFarmerNumber = (countyId: string, sequence: number): string =>
  `${countyId}-${String(sequence).padStart(6, '0')}`;

/** C-8R.2: an administrator moves a farmer's caseload to another officer. */
export const reassignFarmerSchema = z.strictObject({
  officer_id: z
    .string({ error: () => FARMER_MESSAGES.reassignOfficerRequired })
    .regex(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
      FARMER_MESSAGES.reassignOfficerNotUuid,
    ),
});
export type ReassignFarmer = z.infer<typeof reassignFarmerSchema>;
